package io.lker.bjj.models;

public enum BeltRank {
    WHITE0, WHITE1, WHITE2, WHITE3, WHITE4,
    BLUE0, BLUE1, BLUE2, BLUE3, BLUE4,
    PURPLE0, PURPLE1, PURPLE2, PURPLE3, PURPLE4,
    BROWN0, BROWN1, BROWN2, BROWN3, BROWN4,
    BLACK0, BLACK1, BLACK2, BLACK3, BLACK4
}
